### ISSUE TITLE
Do you plan Rails 5 support?

### ISSUE THREAD

**Issue by drgcms** [brianhempel/mongo_session_store#33]
I get this error when running my project with mongo_session_store-rails4 in Rails 5.

RuntimeError (#find_session not implemented.):
  
vendor/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:380:in `find_session'
vendor/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:270:in `load_session'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:56:in `block in load_session'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:64:in `stale_session_check!'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/session/abstract_store.rb:56:in `load_session'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:216:in `load!'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:212:in `load_for_write!'
vendor/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/request/session.rb:114:in `[]='
...
...

It looks like session support was changed in rack 2.

I am using mongoid_store

WwwDrgcms::Application.config.session_store :mongoid_store , {
    expire_after: 1.month
}

and if I disable these lines application is working to some degree.

by
TheR

**Comment by brianhempel** [comment]
The [mongoid/mongo_session_store](https://github.com/mongoid/mongo_session_store) fork will soon have Rails 5 support under the [mongo_session_store](https://rubygems.org/gems/mongo_session_store) gem name.

Will close this issue when a gem is released.

**Comment by tombruijn** [comment]
Experimental support added in PR https://github.com/mongoid/mongo_session_store/pull/31
Let me know if it works :)
